name: Run Linters

on:
  push:
   branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - name: Run all linters
      run: |
        pip install pre-commit
        pre-commit run --all-files --verbose
